### ISSUE TITLE
Design for responsive

### ISSUE THREAD

**Issue by dstorey** [dstorey/HTML5accessibility#12]
Need design for where anything changes beyond just going linear, one column.

Lets avoid doing anything weighty like adjusting type sizes/margins for text unless absolutely needed.

Things we may need to adjust:
- logo and heading text in header
- site nav
- table layout - can we squeeze the full width of the tables in some how? The single column table design will be harder here as has additional column.

Probably ok:

Everything where we do multi-column now, we can collapse to linear design.

**Comment by melanierichards** [comment]
On narrow browsers, probably want to scale down the type size universally a little bit. Anything that's 13px, though, we might want to persist.

For nav: that 2px border that's on the left now becomes a top border for the list (left border goes away). At browsers too narrow for the full layout but where you can fit in two nav items next to each other, those nav items take up 50% of the width and have a dotted line between them. I can mock this up later if it's confusing.

Can do other mockups on Monday.

**Comment by melanierichards** [comment]
@dstorey can make some mockups later today if they seem to be helpful. Anything in particular you'd like to see?

**Comment by melanierichards** [comment]
@dstorey here's a mobile mockup, with and without redlines.

For the most part, I'm trying to scale down type and margins proportionally. So you can set the base font size of the page to 16px or 100% (instead of the 18px at full desktop size) and everything should scale down proportionally.

Where that is not true, I've marked in redlines.

# Exceptions to the rule that are NOT in redlines:
- Line stroke widths are mostly the same; exceptions noted here
- For body copy, the line height is 20px (a little narrower than proportional scaling). The bottom-margins on paragraphs are 16px. You can make those bottom-margins 16px on desktop too, if you'd like.
- Font size for header nav should be maintained

## Browser scores
- Large browser logos the same size as the desktop view
- Browser logo and text are vertically aligned in the middle

## About this project
- NVDA language line height is tighter (18px)
- NVDA ad and language are vertically aligned in the middle

## Feature support
- Key is 2 CSS columns w/ 20px gutter
- Padding around the tables: 8px. Sorry, was too small to fit redlines well.
- All lines the table are half the width of their desktop version
- Padding in table cells: 3px 3px for table head, 8px 3px for table body
- I made the support icons the same size as the smaller version of the icons (circle is 12px wide, dash is 16px wide), but I think in this context they could have a 2px stroke instead of the 3px. I'll let you decide whether or not that's overkill.

## How to test
- Keep all measurements and styles the same for the "Browser dev tools", etc titles.
- 4px margin b/t bullet of list item and text of the list item.
- 8px margin b/t list items.

## Notes
- CC text is same style as NVDA.

![html5 a11y mobile redlines](https://cloud.githubusercontent.com/assets/340395/13831931/963f4df2-eb94-11e5-8416-c6fc8c4c1575.png)
![html5 a11y mobile](https://cloud.githubusercontent.com/assets/340395/13831930/963eddea-eb94-11e5-8d69-c97671d478fd.png)

**Comment by melanierichards** [comment]
@dstorey things I still owe you: "tablet" view, and a nicely-output small logo for that mobile size that looks a little jank above.

**Comment by dstorey** [comment]
@melanierichards : What about something like the following for the table (hacked together in debugger so excuse messy padding, etc, but you get the idea)

![screen shot 2016-03-16 at 7 30 18 pm](https://cloud.githubusercontent.com/assets/465069/13834591/83d81888-ebad-11e5-9372-96bce7b5abfd.png)

Assuming I can remove the criteria header without display none, and do something smarter with the initial none-collapsed criteria label, such as display it under the feature name like the expanded ones  (not sure if i can do that…that one possibly isn't needed as long as i can keep the header in the screen reader)

In this design perhaps the + would be on a new line (before or after) to give more space for the feature name. Icons should be smaller, etc.

**Comment by dstorey** [comment]
Got it to look like this so far. Not solved long feature name labels yet
![screen shot 2016-03-17 at 1 18 35 am](https://cloud.githubusercontent.com/assets/465069/13840181/072be112-ebde-11e5-9391-b627797f599c.png)

**Comment by melanierichards** [comment]
@dstorey that's what I was trying to suggest yesterday and having a hard time communicating in, perhaps. :P I think that makes sense.

**Comment by dstorey** [comment]
@melanierichards it is what I suggested too, but was impossible to do due to tables. But I worked out a magic way of doing it that works (fingers crossed…could blow up in different browsers)

**Comment by dstorey** [comment]
I believe there is no size for the main header text or at least it is way bigger when not resizing it. Also the width of the logo…but i think you said you were doing something else for that? As it is a bg image the margin at the bottom looks way bigger too.

**Comment by dstorey** [comment]
Closing this now have separate bug for tablet design
