### ISSUE TITLE
Design for tablet-ish sizes

### ISSUE THREAD

**Issue by dstorey** [dstorey/HTML5accessibility#31]
Might just be a combination between mobile and desktop styles.

Main thing that looks bad currently is the result cards. They are left aligned so have huge gap to right. I tried max width and centering but that looked weird. Possibly either do a two column with mobile or desktop card layout.

**Comment by dstorey** [comment]
Other pain area is the tables. Could either hide the criteria main column earlier or just reduce the feature text size (possibly in combination with the + positioning, but that might require hiding the criteria column)

**Comment by melanierichards** [comment]
@dstorey Here's the tablet design, with and without redlines. All type and margin/padding sizes match the mobile designs unless otherwise stated.

What might not be obvious from redlines:
- Table check, x, etc. icons are the larger desktop sizes (browser icons are a little smaller though, as labelled).
- Padding in table is 8px.
- "Accessibly supported" etc. in table is 12px font size.
- I'm showing the browser cards in thirds; you could have an additional breakpoint where they are halves if they get too skinny but you feel it's too wide for the mobile layout.
- The last columns are a little unbalanced so feel free to shuffle around as you see fit. I was trying to be easy on your markup.

![html5 a11y redlines - tablet](https://cloud.githubusercontent.com/assets/340395/13934494/b9ff433a-ef6f-11e5-8f7d-456f9db4b0bb.png)

![html5 a11y tablet](https://cloud.githubusercontent.com/assets/340395/13934490/b3c35f92-ef6f-11e5-9f75-2c85e9cedc08.png)

**Comment by dstorey** [comment]
@melanierichards what sizes should it enter and leave the tablet styles?

Would it be possible to keep the current layout of desktop for How to Test, except two column (browser and desktop in 2nd column). I don't have any elements to apply two different multi-columns to, so I don't think this is possible without changing the markup

**Comment by melanierichards** [comment]
@dstorey I designed this at 800px but I always make this decision in-browser. I place breakpoints where things start looking bad. If you're not feeling confident about where you're placing breakpoints we can do a code-pairing thing and tweak those #s together.

I'm fine with the layout you're suggesting for "how to test".
