### ISSUE TITLE
Tablet view adjustments

### ISSUE THREAD

**Issue by melanierichards** [dstorey/HTML5accessibility#42]
- [ ] Put the line in from the design above the page nav.
- [ ] Put a 2px full-width border above the Creative Commons license info.
- [ ] The size of the "About this project" text on tablet/mobile is 18px font size, 24px line height.

**Comment by dstorey** [comment]
What is the "about this project" text?

**Comment by dstorey** [comment]
@melanierichards I tried the 2px border and it ended up looking weird and stripes, with the thicker border not far above and the round icons right below it.

also takes a bunch of extra code to fudge as needs to be added and taken away (as currently no specific styles to mobile, and the footer is only 50% to share code with parts above and put it in the columns, so that would require more override code.

As the original designs didn't require a line, can we do without and change whatever margin you want. Currently there isn;t a tablet design as you had it in the right column in the redlines.
